name: Deploy Docs

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  docs:
    uses: steamroller-animation-pipeline/workflows/.github/workflows/deploy_docs.yml@main
    secrets: inherit
